---
title: "Testing the buttons"
author: "Leon"
date: "2023-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
buttons <- function(df, new_cols = c("GC", "UNIPROT")){
  
  .actionbutton_biocstyle <- "color: #ffffff; background-color: #0092AC"
  
  val <- df$SYMBOL
  if( "GC" %in% new_cols){
    for (i in 1:length(df$SYMBOL)) {
      
      #GeneCards
      df$SYMBOL_GC[i] <- sprintf(
        '<a href = "https://www.genecards.org/cgi-bin/carddisp.pl?gene=%s" target = "_blank" class = "btn     btn-primary" style = "%s">%s</a>',
        val[i],
        .actionbutton_biocstyle,
        val[i]
      )
    }
  }
  if( "NCBI" %in% new_cols){
    
    #NCBI
    for (i in 1:length(df$SYMBOL)) {
      
      df$SYMBOL_NCBI[i] <- paste0('<a href="http://www.ncbi.nlm.nih.gov/gene/?term=',val[i],'[sym]" target="_blank" class="btn btn-primary">',val[i],'</a>')
    }
  }
  
  if( "GTEX" %in% new_cols){
    
    #GTEx 
    for (i in 1:length(df$SYMBOL)) {
      df$SYMBOL_GTEX[i] <- sprintf(
        '<a href = "https://www.gtexportal.org/home/gene/%s" target = "_blank" class = "btn btn-primary" style = "%s"><i class="fa fa-dna"></i>%s</a>',
        val[i],
        .actionbutton_biocstyle,
        val[i]
      )
    }
  }
  if( "UNIPROT" %in% new_cols){
    
    #Uniprot
    for (i in 1:length(df$SYMBOL)) {
      df$SYMBOL_UniProt[i] <- sprintf('<a href = "https://www.uniprot.org/uniprot/?query=%s&sort=score" target = "_blank" class = "btn btn-primary" style = "%s"><i class="fa fa-spinner"></i>%s</a>',
                                      val[i],
                                      .actionbutton_biocstyle,
                                      val[i])
    }
  }
  if( "dbPTM" %in% new_cols){
    
    #dbPTM 
    for (i in 1:length(df$SYMBOL)) {
      df$SYMBOL_dbPTM[i] <- sprintf('<a href = "http://dbptm.mbc.nctu.edu.tw/info.php?id=%s_HUMAN" target = "_blank" class = "btn btn-primary" style = "%s"><i class="fa fa-edit"></i>%s</a>',
                                    val[i],
                                    .actionbutton_biocstyle,
                                    val[i])
    }
  }
  if( "HPA" %in% new_cols){
    
    #Human protein atlas Portal
    for (i in 1:length(df$SYMBOL)) {
      df$SYMBOL_HPA[i] <- sprintf('<a href = "https://www.proteinatlas.org/search/%s" target = "_blank" class = "btn btn-primary" style = "%s"><i class="fa fa-cubes"></i>%s</a>',
                                  val[i],
                                  .actionbutton_biocstyle,
                                  val[i])
    }
  }
  df <- df %>%
    select(-SYMBOL)
  return(df)
}


```

```{r}
 library(dplyr)
library(DESeq2)
library(devtools)
devtools::load_all()
library(mosdef)
 data("gse", package = "macrophage")

 dds_macrophage <- DESeqDataSet(gse, design = ~line + condition)
#changing the ids to Ensembl instead of the Gencode used in the object
 rownames(dds_macrophage) <- substr(rownames(dds_macrophage), 1, 15)
 dds_macrophage
 keep <- rowSums(counts(dds_macrophage) >= 10) >= 6
 dds_macrophage <- dds_macrophage[keep, ]
 dds_macrophage
 dds_macrophage <- DESeq(dds_macrophage)

 res_macrophage_IFNg_vs_naive <- results(dds_macrophage,
                                         contrast = c("condition", "IFNg", "naive"),
                                         lfcThreshold = 1, alpha = 0.05)
 res_macrophage_IFNg_vs_naive$SYMBOL <- rowData(dds_macrophage)$SYMBOL
 res_df <- as.data.frame(res_macrophage_IFNg_vs_naive@listData)
 res_df$ensembleID <- res_macrophage_IFNg_vs_naive@rownames
  res_df<-res_df %>%
          relocate(ensembleID, .before= baseMean)
  res_df <-res_df[1:100,]
 # res_df$SYMBOL <- create_link_NCBI(res_df$SYMBOL)
 res_df$ensembleID <- create_link_ENS(res_df$ensembleID, species= "Homo_sapiens")
 res_df <-buttons(res_df)

 DT::datatable(res_df)
```

